"""
Email Template Module
HTML and plain text email templates for sending analysis results
"""

from datetime import datetime
from jinja2 import Template


def render_html_email(critical_count, important_count, minor_count, overall_assessment, recipient_name="there"):
    """
    Render HTML email template with analysis summary

    Args:
        critical_count: Number of critical issues
        important_count: Number of important issues
        minor_count: Number of minor issues
        overall_assessment: Overall assessment text
        recipient_name: Name of recipient (default: "there")

    Returns:
        HTML string for email body
    """

    # HTML template with inline CSS (required for email clients)
    html_template = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f5f5f5;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); max-width: 600px;">

          <!-- Header -->
          <tr>
            <td style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px 30px; text-align: center; border-radius: 8px 8px 0 0;">
              <h1 style="margin: 0 0 10px 0; font-size: 28px; font-weight: bold;">Home Inspection Analysis Report</h1>
              <p style="margin: 0; font-size: 16px; opacity: 0.95;">AI-Powered Analysis for Your Home Purchase Decision</p>
            </td>
          </tr>

          <!-- Content -->
          <tr>
            <td style="padding: 40px 30px;">
              <p style="margin: 0 0 20px 0; font-size: 16px;">Hello {{ recipient_name }},</p>

              <p style="margin: 0 0 20px 0; font-size: 16px;">Your home inspection report has been analyzed using Claude AI. Here's your summary:</p>

              <!-- Summary Table -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f9f9f9; border-collapse: collapse; margin: 20px 0; border-radius: 4px; overflow: hidden;">
                <tr>
                  <td style="padding: 15px; border-bottom: 1px solid #ddd; font-weight: bold; color: #667eea; font-size: 15px; width: 70%;">Critical Issues:</td>
                  <td style="padding: 15px; border-bottom: 1px solid #ddd; font-size: 24px; font-weight: bold; color: #dc3545; text-align: right;">{{ critical_count }}</td>
                </tr>
                <tr>
                  <td style="padding: 15px; border-bottom: 1px solid #ddd; font-weight: bold; color: #667eea; font-size: 15px;">Important Issues:</td>
                  <td style="padding: 15px; border-bottom: 1px solid #ddd; font-size: 24px; font-weight: bold; color: #ff9800; text-align: right;">{{ important_count }}</td>
                </tr>
                <tr>
                  <td style="padding: 15px; font-weight: bold; color: #667eea; font-size: 15px;">Minor Issues:</td>
                  <td style="padding: 15px; font-size: 24px; font-weight: bold; color: #2196f3; text-align: right;">{{ minor_count }}</td>
                </tr>
              </table>

              <!-- Overall Assessment -->
              <div style="background-color: #f0f4ff; padding: 20px; border-left: 4px solid #667eea; margin: 25px 0; border-radius: 4px;">
                <p style="margin: 0 0 10px 0; font-weight: bold; font-size: 16px; color: #667eea;">Overall Assessment:</p>
                <p style="margin: 0; font-size: 15px; line-height: 1.6;">{{ overall_assessment }}</p>
              </div>

              <p style="margin: 20px 0; font-size: 16px;"><strong>The full detailed analysis is attached as a PDF.</strong></p>

              <p style="margin: 20px 0; font-size: 14px; color: #666;">Review the attached PDF for complete details on each issue, including cost estimates and priority recommendations.</p>

            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background-color: #f5f5f5; padding: 25px 30px; text-align: center; border-top: 1px solid #ddd; border-radius: 0 0 8px 8px;">
              <p style="margin: 0 0 10px 0; font-size: 14px; color: #666;">This analysis was generated by <strong>Home Inspection Analyzer</strong> using Claude AI.</p>
              <p style="margin: 0; font-size: 12px; color: #999;">Generated on {{ generated_date }}</p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
    """

    template = Template(html_template)

    # Truncate overall assessment if too long (for email display)
    if len(overall_assessment) > 300:
        overall_assessment = overall_assessment[:297] + "..."

    return template.render(
        recipient_name=recipient_name,
        critical_count=critical_count,
        important_count=important_count,
        minor_count=minor_count,
        overall_assessment=overall_assessment,
        generated_date=datetime.now().strftime('%B %d, %Y at %I:%M %p')
    )


def render_text_email(critical_count, important_count, minor_count, overall_assessment, recipient_name="there"):
    """
    Render plain text email as fallback for clients that don't support HTML

    Args:
        critical_count: Number of critical issues
        important_count: Number of important issues
        minor_count: Number of minor issues
        overall_assessment: Overall assessment text
        recipient_name: Name of recipient (default: "there")

    Returns:
        Plain text string for email body
    """

    text_template = """
HOME INSPECTION ANALYSIS REPORT
================================

Hello {{ recipient_name }},

Your home inspection report has been analyzed using Claude AI. Here's your summary:

ISSUE SUMMARY
-------------
Critical Issues:    {{ critical_count }}
Important Issues:   {{ important_count }}
Minor Issues:       {{ minor_count }}

OVERALL ASSESSMENT
------------------
{{ overall_assessment }}

The full detailed analysis is attached as a PDF.

Review the attached PDF for complete details on each issue, including cost estimates and priority recommendations.

---
This analysis was generated by Home Inspection Analyzer using Claude AI.
Generated on {{ generated_date }}
    """

    template = Template(text_template)

    return template.render(
        recipient_name=recipient_name,
        critical_count=critical_count,
        important_count=important_count,
        minor_count=minor_count,
        overall_assessment=overall_assessment,
        generated_date=datetime.now().strftime('%B %d, %Y at %I:%M %p')
    )
